dynamic jsondata = {
  "key": "299:AZRX3W",
  "seriesNumber": "299",
  "confirmationNumber": "AZRX3W",
  "bookingAgent": "ezygtwy",
  "crsCode": "",
  "travelGroupID": 0,
  "iataNumber": "",
  "externalAppID": "",
  "webBookingID": "a88f0199c26ai654yftaqeaby5ydoce2ta83a995c5d9",
  "promotionalID": 0,
  "promotionalCode": null,
  "recieptLanguageID": 1033,
  "reservationCurrency": 152,
  "profileID": -9223372036854775808,
  "pnrPin": 156625,
  "bookDate": "2023-08-11T07:49:07",
  "reservationType": "EXT_WEB",
  "todaysDate": "2023-08-23T15:31:35.9618314+07:00",
  "lastModified": "2023-08-11T08:21:36",
  "reservationExpirationDate": "0001-01-01T00:00:00",
  "corporationID": "",
  "securityGuid": "a88f0199c26ai654yftaqeaby5ydoce2ta83a995c5d9",
  "hasTickets": false,
  "valuePackageData": null,
  "userIPAddress": null,
  "manageBookingAgent": null,
  "historicConfirmationNum": "",
  "cabin": "ECONOMY",
  "reservationBalance": 0,
  "changeFee": 0,
  "logicalFlightCount": 1,
  "activePassengerCount": 1,
  "balancedReservation": true,
  "reservationFulfillmentRequiredByGMT": "0001-01-01T00:00:00",
  "reservationFulfillmentRequiredByODT": "0001-01-01T00:00:00",
  "airlines": [
    {
      "key": null,
      "logicalFlight": [
        {
          "key": "75385:8/25/2023 5:45:00 PM",
          "recordNumber": 0,
          "logicalFlightID": 75385,
          "departureDate": "2023-08-25T00:00:00",
          "origin": "SGN",
          "originDefaultTerminal": null,
          "originName": "Tan Son Nhat International Airport",
          "destination": "HAN",
          "destinationDefaultTerminal": null,
          "destinationName": "Noi Bai International Airport",
          "originMetroGroup": "SGN",
          "destinationMetroGroup": null,
          "sellingCarrier": "VU",
          "operatingCarrier": "VU",
          "operatingFlightNumber": "780",
          "departureTime": "2023-08-25T17:45:00",
          "arrivaltime": "2023-08-25T19:55:00",
          "packageItemID": 0,
          "packageItemName": null,
          "packageItemDescription": null,
          "packageItemBookDate": "0001-01-01T00:00:00",
          "packageItemStartDate": "0001-01-01T00:00:00",
          "packageItemEndDate": "0001-01-01T00:00:00",
          "vendorId": 0,
          "vendorName": null,
          "active": true,
          "vendorDescription": null,
          "uiDisplayValue": 0,
          "physicalFlights": [
            {
              "key": "75385:69679:8/25/2023 5:45:00 PM",
              "recordNumber": 0,
              "destinationDefaultTerminal": "",
              "physicalFlightID": 69679,
              "logicalFlightID": 75385,
              "carrierCode": "VU",
              "carrierName": null,
              "flightNumber": "780",
              "flightOrder": 1,
              "departureDate": "2023-08-25T00:00:00",
              "origin": "SGN",
              "originDefaultTerminal": "",
              "originName": "Tan Son Nhat International Airport",
              "destination": "HAN",
              "destinationName": "Noi Bai International Airport",
              "originMetroGroup": "SGN",
              "destinationMetroGroup": "HAN",
              "sellingCarrier": "VU",
              "operatingCarrier": "VU",
              "operatingFlightNumber": "780",
              "departureTime": "2023-08-25T17:45:00",
              "arrivaltime": "2023-08-25T19:55:00",
              "flightDuration": 7800,
              "trip": -2147483648,
              "gate": "",
              "totalWeight": 0,
              "uiDisplayValue": 0,
              "active": true,
              "customers": [
                {
                  "key": "9132b304-c83e-41ba-852e-015782f1b9e6",
                  "airlinePersons": [
                    {
                      "weight": -792281625142643,
                      "ffNum": "",
                      "paxActive": true,
                      "recordNumber": 1,
                      "recordLocator": "",
                      "originalRecordNumber": 0,
                      "contactInfo": "",
                      "dropoffID": 0,
                      "pickupID": 0,
                      "lapChildID": -2147483648,
                      "fareClassCode": "A ",
                      "fareBasisCode": "APRO",
                      "webFareType": "121:NON-REFUNDABLE",
                      "fareBasisSched": "10403",
                      "fareAmount": 80000,
                      "resSegStatus": 4,
                      "segSubStatus": 1,
                      "selecteeStatus": 0,
                      "checkinStatus": false,
                      "cabin": "ECONOMY",
                      "ticketNumber": "",
                      "hasTickets": false,
                      "uiDisplayValue": -2147483648,
                      "interlinedSegment": 0,
                      "interlinedCarrierCode": "",
                      "manualFare": 0,
                      "inventoryOverbooked": 0,
                      "ticketCouponNumber": "",
                      "ticketControl": 0,
                      "ticketControlOwner": "",
                      "ticketControlModifiedDate": "0001-01-01T00:00:00",
                      "marketingCode": "1",
                      "marketingOptIn": false,
                      "emergencyContactID": 695080,
                      "disclosedEmergencyContact": -2147483648,
                      "cappsStatus": -2147483648,
                      "toRecordNumber": 0,
                      "fromRecordNumber": 0,
                      "storeFrontID": "1",
                      "insuranceConfNum": "",
                      "insuranceTransID": "",
                      "redressNum": "",
                      "knownTravNum": "",
                      "primaryPassenger": true,
                      "nameChangeCount": 0,
                      "crsCode": "",
                      "seatAssignments": [
                        {
                          "key": "69679:695079",
                          "physicalFlightID": 69679,
                          "actualDepartureDate": "2023-08-25T17:45:00",
                          "flightNumber": null,
                          "scheduledDeparturetime": "2023-08-25T17:45:00",
                          "scheduledArrivaltime": "2023-08-25T19:55:00",
                          "boardingPassNumber": 1,
                          "seat": "A",
                          "rowNumber": 1,
                          "gate": "",
                          "oldSeat": null,
                          "oldRowNumber": 0,
                          "boarded": false,
                          "checkInAgent": "",
                          "checkInDate": "2023-08-11T08:21:36",
                          "couponStatusIndicator": "NC",
                          "boardingSequence": "O8GN",
                          "lastModifiedDate": "0001-01-01T00:00:00",
                          "boardingPassPrinted": 0,
                          "frequentFlyerCarrierCode": "",
                          "frequentFlyerNumber": "",
                          "frequentFlyerSSRCode": "",
                          "frequentFlyerMemberTierLevel": "",
                          "frequentFlyerMemberRating": "",
                          "frequentFlyerNumberActionTracker": 0,
                          "reservationChannelID": 0,
                          "frequentFlyerInfoReservationChannelID": 0,
                          "frequentFlyerNumberLAstModifiedDate":
                              "0001-01-01T00:00:00",
                          "seatChargeID": 0,
                          "seatMarketingAttributes": [],
                          "seatCommercialAttributes": [],
                          "railCarID": null,
                          "railCarSequence": null
                        }
                      ],
                      "charges": [
                        {
                          "key": "7744097",
                          "reservationChargeID": 7744097,
                          "originalChargeID": 0,
                          "codeType": "TAX       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 0,
                          "taxID": 1001,
                          "chargeComment":
                              "<![CDATA[AX: Passenger Service charge]]>",
                          "amount": 50000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:48:11",
                          "originalAmount": 50000,
                          "description": "AX: Passenger Service charge",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": 7744092,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": true,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744097:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 50000,
                              "reservationChargeID": 7744097,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": "AX  "
                        },
                        {
                          "key": "7744094",
                          "reservationChargeID": 7744094,
                          "originalChargeID": 0,
                          "codeType": "TAX       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 0,
                          "taxID": 623,
                          "chargeComment":
                              "<![CDATA[C4: Passenger and baggage security screening service charges DOM ADT]]>",
                          "amount": 20000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:48:11",
                          "originalAmount": 20000,
                          "description":
                              "C4: Passenger and baggage security screening service charges DOM ADT",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": 7744092,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": true,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744094:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 20000,
                              "reservationChargeID": 7744094,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": "C4  "
                        },
                        {
                          "key": "7744095",
                          "reservationChargeID": 7744095,
                          "originalChargeID": 0,
                          "codeType": "TAX       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 0,
                          "taxID": 781,
                          "chargeComment":
                              "<![CDATA[YR02: System and Admin surcharges domestic 2]]>",
                          "amount": 420000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:48:11",
                          "originalAmount": 420000,
                          "description":
                              "YR02: System and Admin surcharges domestic 2",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": 7744092,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": true,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744095:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 420000,
                              "reservationChargeID": 7744095,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": "YR02"
                        },
                        {
                          "key": "7744098",
                          "reservationChargeID": 7744098,
                          "originalChargeID": 0,
                          "codeType": "BAGF      ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 1,
                          "taxID": -2147483648,
                          "chargeComment": "<![CDATA[FARE BUNDLE - BABG]]>",
                          "amount": 0,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:48:11",
                          "originalAmount": 0,
                          "description":
                              "MIEN PHI 20KG HANH LY KY GUI - 20KG FREE BAGGAGE",
                          "statusReasonID": 0,
                          "isSSR": true,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": -2147483648,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": true,
                          "taxIsRefundable": false,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744098:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 0,
                              "reservationChargeID": 7744098,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 999,
                          "physicalFlightID": 69679,
                          "extPenaltyRule": "",
                          "taxCode": ""
                        },
                        {
                          "key": "7744092",
                          "reservationChargeID": 7744092,
                          "originalChargeID": 0,
                          "codeType": "AIR       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 1,
                          "taxID": -2147483648,
                          "chargeComment": "<![CDATA[WEB:AIR]]>",
                          "amount": 80000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T00:00:00",
                          "originalAmount": 80000,
                          "description": "WEB:AIR",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": -2147483648,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": false,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744092:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 80000,
                              "reservationChargeID": 7744092,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": ""
                        },
                        {
                          "key": "7744096",
                          "reservationChargeID": 7744096,
                          "originalChargeID": 0,
                          "codeType": "TAX       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 0,
                          "taxID": 801,
                          "chargeComment":
                              "<![CDATA[UE: Value Added Tax (Domestic) 8%]]>",
                          "amount": 6400,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:48:11",
                          "originalAmount": 6400,
                          "description": "UE: Value Added Tax (Domestic) 8%",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": 7744092,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": true,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744096:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 6400,
                              "reservationChargeID": 7744096,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": "UE  "
                        },
                        {
                          "key": "7744093",
                          "reservationChargeID": 7744093,
                          "originalChargeID": 0,
                          "codeType": "TAX       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 0,
                          "taxID": 621,
                          "chargeComment":
                              "<![CDATA[AX: Passenger service charges (domestic) ADT NHÓM A]]>",
                          "amount": 100000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:48:11",
                          "originalAmount": 100000,
                          "description":
                              "AX: Passenger service charges (domestic) ADT NHÓM A",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": 7744092,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": true,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744093:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 100000,
                              "reservationChargeID": 7744093,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": "AX  "
                        },
                        {
                          "key": "7744099",
                          "reservationChargeID": 7744099,
                          "originalChargeID": 0,
                          "codeType": "PMNT      ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 1,
                          "taxID": -2147483648,
                          "chargeComment": "<![CDATA[Payment Fee]]>",
                          "amount": 50000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:49:00",
                          "originalAmount": 50000,
                          "description": "Payment Fee",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": -2147483648,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": false,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744099:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 50000,
                              "reservationChargeID": 7744099,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": ""
                        },
                        {
                          "key": "7744100",
                          "reservationChargeID": 7744100,
                          "originalChargeID": 0,
                          "codeType": "TAX       ",
                          "refundPersonOrgID": -2147483648,
                          "refundType": "OriginalCharge",
                          "currencyCode": "VND",
                          "originalCurrency": "VND",
                          "recordNumber": 1,
                          "voucherNumber": -2147483648,
                          "billDate": "2023-08-11T07:49:07",
                          "rpm": 1,
                          "taxID": 801,
                          "chargeComment": "<![CDATA[]]>",
                          "amount": 4000,
                          "chargeStatus": 1,
                          "isRefundable": 0,
                          "exchangeRate": 1,
                          "exchangeRateDate": "2023-08-11T07:49:00",
                          "originalAmount": 4000,
                          "description": "Value Added Tax (Domestic) 8%",
                          "statusReasonID": 0,
                          "isSSR": false,
                          "paymentNumber": -2147483648,
                          "logicalFlightID": -2147483648,
                          "includeInPenalty": false,
                          "taxChargeID": 7744099,
                          "taxIncludedInFare": false,
                          "commission": 0,
                          "resChannelId": 8,
                          "commissionDueRptCurrency": 0,
                          "commissionDueResCurrency": 0,
                          "nonRefundableResCurrency": 0,
                          "nonRefundableRptCurrency": 0,
                          "refundableResCurrency": 0,
                          "refundableRptCurrency": 0,
                          "penaltyResCurrency": 0,
                          "penaltyRptCurrency": 0,
                          "commissionable": false,
                          "nonDiscountedResAmt": 0,
                          "nonDiscountedRptAmt": 0,
                          "bundled": false,
                          "taxIsRefundable": true,
                          "taxIsCommissionable": false,
                          "serviceIsRefundable": false,
                          "serviceIsCommissionable": false,
                          "reservationPaymentMaps": [
                            {
                              "key": "7744100:979654",
                              "reservationPaymentID": 979654,
                              "amountApplied": 4000,
                              "reservationChargeID": 7744100,
                              "datePaid": "2023-08-11T07:49:10",
                              "originalReferencePaymentID": 0,
                              "refundAmount": 0
                            }
                          ],
                          "penaltyChargeID": 0,
                          "penaltyTypeID": 0,
                          "boardingPassSsrOrder": 0,
                          "physicalFlightID": 0,
                          "extPenaltyRule": "",
                          "taxCode": "UE  "
                        }
                      ],
                      "bags": [],
                      "checkInLocator": "AZRX3W",
                      "fareBundleCode": "BABG",
                      "height": -2147483648,
                      "promotionType": "",
                      "key": "695079:1",
                      "personOrgID": 695079,
                      "firstName": "HA",
                      "lastName": "XINH",
                      "middleName": "",
                      "age": 33,
                      "dob": "1990-04-18T00:00:00",
                      "gender": "F",
                      "title": "MRS",
                      "nationalityLaguageID": -2147483648,
                      "relationType": "SELF",
                      "wbcid": -2147483648,
                      "ptcid": 1,
                      "useInventory": false,
                      "address": "MINH TAM",
                      "address2": "MISSING ADDRESS2",
                      "city": "HCM",
                      "state": "NA",
                      "postal": "00000",
                      "country": "VN",
                      "company": "",
                      "comments": "<![CDATA[]]>",
                      "passport": "",
                      "nationality": "",
                      "profileId": -9223372036854775808
                    }
                  ]
                }
              ],
              "fromTerminal": "",
              "toTerminal": "",
              "airCraftType": "32B",
              "airCraftDescription": "AIRBUS A321",
              "utcDepartureOffset": "7",
              "utcArrivalOffset": "7",
              "deiDisclosure": null
            }
          ],
          "flightDisruptionAlert": null
        }
      ],
      "oaFlights": []
    }
  ],
  "payments": [
    {
      "key": "979654",
      "reservationPaymentID": 979654,
      "cardHolder": "dummy",
      "paymentAmount": 730400,
      "expirationDate": "2050-12-01T00:00:00",
      "cardNumber": "4********1",
      "cvCode": null,
      "authorizationcode": "12345",
      "terminalID": -2147483648,
      "currencyPaid": "VND",
      "checkNumber": -2147483648,
      "reference": "AZRX3W:979654                                     ",
      "result": "",
      "transactionID": "1",
      "valueCode": null,
      "transactionIndicator": -2147483648,
      "settlementBatch": null,
      "authorizedAmount": -79228162514264,
      "voucherNumber": -2147483648,
      "ffNumber": null,
      "miles": -2147483648,
      "paymentComment": "<![CDATA[]]>",
      "baseCurrency": "VND",
      "baseAmount": 730400,
      "exchangeRate": 1,
      "exchangeRateDate": "2023-08-11T07:49:10",
      "documentReceivedBy": null,
      "batchProcessStart": "0001-01-01T00:00:00",
      "batchProcessExtracted": 0,
      "ticketCouponNumber": null,
      "atcanDateProcessed": "0001-01-01T00:00:00",
      "ticketType": null,
      "gcxID": "",
      "gcxOptOption": "",
      "gcxExported": -2147483648,
      "gcxExportedDate": "0001-01-01T00:00:00",
      "originalCurrency": "",
      "originalAmount": 0,
      "iataNum": "",
      "processorID": "",
      "merchantID": "ezy",
      "processorName": "",
      "originalPaymentMethod": null,
      "transactionStatus": 1,
      "responseMessage": "",
      "responseCode": "",
      "personOrgID": 695081,
      "firstName": "HA",
      "lastName": "XINH",
      "companyName": "",
      "address": "MINH TAM",
      "address2": "",
      "city": "HCM",
      "state": "NA",
      "postal": "00000",
      "country": "VN",
      "paymentMethod": "VISA",
      "datePaid": "2023-08-11T07:49:10",
      "userData": null,
      "cardVerification": null,
      "grossAmtResCurrency": 0,
      "grossAmtPayCurrency": 0,
      "netAmtResCurrency": 0,
      "commissionDeductedResCurrency": 0,
      "commissionDeductedPayCurrency": 0,
      "rptNetFrmResCurrency": 0,
      "rptCommissionFromResCurrency": 0,
      "rptCommissionFromPayCurrency": 0,
      "totalRefundResCurrency": 0,
      "totalRefundRptCurrency": 0,
      "totalRefundPayCurrency": 0,
      "redeemedVoucherAmount": 0,
      "userID": "ezy",
      "originalPaymentID": 0,
      "paymentReservationChannelID": 8,
      "ancillaryData01": "",
      "ancillaryData02": "",
      "ancillaryData03": "",
      "ancillaryData04": "",
      "ancillaryData05": "",
      "metaData": []
    }
  ],
  "history": [
    {
      "historyID": 0,
      "key": "3910686",
      "recordNumber": -2147483648,
      "historyType": 9,
      "activityDate": "2023-08-11T07:49:10",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Payer Name: HA XINH VISA  Amount: 730400.00 VISA VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910692",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T08:21:36",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "vta0144",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Total Charges: 730400.00 VND Total Payments: 730400.00 VND Balance Due: .00 VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910694",
      "recordNumber": 1,
      "historyType": 0,
      "activityDate": "2023-08-11T08:21:36",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[VU 780 SGN - HAN 25-Aug-2023 17:45 19:55 ADT ]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "web",
      "personOrgID": 695079,
      "details": "<![CDATA[For SGN-HAN added Seat 1 A]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910681",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:07",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Added to Payment Check Queue (11-Aug-2023 19:49:07).]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910678",
      "recordNumber": 1,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:07",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment":
          "<![CDATA[VU 780 SGN- HAN 25-Aug 23 Fri 17:45 19:55 Fri 25-Aug 23 ADT ]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": 695079,
      "details":
          "<![CDATA[ AIR APRO 80000 VND  TAX AX 100000 VND  TAX C4 20000 VND  TAX 420000 VND  TAX UE 6400.00 VND  TAX AX 50000 VND  BAGF 0 VND  PMNT 50000 VND  TAX 4000.00 VND  PointOfOrigin:VN PointOfPurchase:704 Total Charge Summary: 730400.00 VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910688",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:13",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "",
      "personOrgID": -2147483648,
      "details": "<![CDATA[Removed from Payment Check Queue.]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910685",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:10",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Total Charges: 730400.00 VND Total Payments: .00 VND Balance Due: .00 VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910691",
      "recordNumber": -2147483648,
      "historyType": 2000,
      "activityDate": "2023-08-11T07:49:17",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "NS",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Email Message sent to nhnhan@gmail.com for Receipt.]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910687",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:13",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "web",
      "personOrgID": -2147483648,
      "details": "<![CDATA[Res PaymentID: 979654]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910680",
      "recordNumber": 1,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:07",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[VU 780 SGN - HAN 25-Aug-2023]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": 695079,
      "details":
          "<![CDATA[Total Charges: 730400.00 VND Total Payments: .00 VND Balance Due: 730400.00 VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910689",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:13",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Payment Time Limit: Changed from 11Aug23 19:49 GMT to --No Due Date--]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910695",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T08:21:36",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "vta0144",
      "personOrgID": -2147483648,
      "details": "<![CDATA[Payment Time Limit: --No Due Date-- ]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910679",
      "recordNumber": 1,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:07",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment":
          "<![CDATA[VU 780 SGN- HAN 25-Aug 23 Fri 17:45 19:55 Fri 25-Aug 23]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": 695079,
      "details": "<![CDATA[BAGF - 0 VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910693",
      "recordNumber": 1,
      "historyType": 0,
      "activityDate": "2023-08-11T08:21:36",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[VU 780 SGN - HAN 25-Aug-2023 17:45 19:55 ADT ]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "vta0144",
      "personOrgID": 695079,
      "details":
          "<![CDATA[For VU 780 SGN - HAN 25-Aug-2023 17:45 19:55 ADT  Seat 1A Checked In]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910682",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:07",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Payment Time Limit: 11Aug23 19:49 GMT (Based on:APRO rule id:1930)]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910684",
      "recordNumber": 1,
      "historyType": 1,
      "activityDate": "2023-08-11T07:49:09",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[VU 780 SGN-HAN 25-AUG-23 17:45:00]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "web",
      "personOrgID": 695079,
      "details": "<![CDATA[Created APIS Info.]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910690",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:14",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "web",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Inserted record into Queue for Email Notification.  Result: Success]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "3910683",
      "recordNumber": -2147483648,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:08",
      "passenger": "",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "ezygtwy",
      "personOrgID": -2147483648,
      "details":
          "<![CDATA[Total Charges: 730400.00 VND Total Payments: .00 VND Balance Due: 730400.00 VND]]>",
      "reservationChannelID": 0
    },
    {
      "historyID": 0,
      "key": "549743",
      "recordNumber": 1,
      "historyType": 0,
      "activityDate": "2023-08-11T07:49:09",
      "passenger": "HA XINH",
      "firstName": null,
      "lastName": null,
      "segment": "<![CDATA[VU 780 SGN - HAN 25-Aug-2023]]>",
      "userIPAddress": null,
      "action": null,
      "userID": "web",
      "personOrgID": 695079,
      "details": "<![CDATA[Created APIS Info.]]>",
      "reservationChannelID": 0
    }
  ],
  "comments": [
    {
      "commentID": 0,
      "key": "f902bddd-97cf-4876-b024-c0e885c428c4",
      "commentDate": "2023-08-11T07:49:07",
      "comment": "<![CDATA[Payment Fee]]>",
      "commentLength": 11,
      "userID": "ezygtwy"
    }
  ],
  "gdsHistory": [],
  "reservationContacts": [
    {
      "vendorID": 0,
      "marketingOptIn": false,
      "redressNum": "",
      "knownTravNum": "",
      "contactInfos": [],
      "key": "695080",
      "personOrgID": 695080,
      "firstName": "HA",
      "lastName": "XINH",
      "middleName": "",
      "age": 30,
      "dob": "1900-01-01T00:00:00",
      "gender": "M",
      "title": "MRS",
      "nationalityLaguageID": -2147483648,
      "relationType": "Self",
      "wbcid": 0,
      "ptcid": 1,
      "useInventory": false,
      "address": "",
      "address2": "",
      "city": "",
      "state": "",
      "postal": "",
      "country": "",
      "company": "EZY",
      "comments": "<![CDATA[]]>",
      "passport": null,
      "nationality": null,
      "profileId": 0
    },
    {
      "vendorID": 0,
      "marketingOptIn": false,
      "redressNum": "",
      "knownTravNum": "",
      "contactInfos": [],
      "key": "695079",
      "personOrgID": 695079,
      "firstName": "HA",
      "lastName": "XINH",
      "middleName": "",
      "age": 33,
      "dob": "1990-04-18T00:00:00",
      "gender": "F",
      "title": "MRS",
      "nationalityLaguageID": -2147483648,
      "relationType": "SELF",
      "wbcid": 0,
      "ptcid": 1,
      "useInventory": false,
      "address": "MINH TAM",
      "address2": "MISSING ADDRESS2",
      "city": "HCM",
      "state": "NA",
      "postal": "00000",
      "country": "VN",
      "company": "",
      "comments": "<![CDATA[]]>",
      "passport": null,
      "nationality": null,
      "profileId": 0
    },
    {
      "vendorID": 0,
      "marketingOptIn": false,
      "redressNum": "",
      "knownTravNum": "",
      "contactInfos": [],
      "key": "695081",
      "personOrgID": 695081,
      "firstName": "HA",
      "lastName": "XINH",
      "middleName": "",
      "age": -2147483648,
      "dob": "0001-01-01T00:00:00",
      "gender": "U",
      "title": "",
      "nationalityLaguageID": -2147483648,
      "relationType": "",
      "wbcid": 0,
      "ptcid": 1,
      "useInventory": false,
      "address": "MINH TAM",
      "address2": "",
      "city": "HCM",
      "state": "NA",
      "postal": "00000",
      "country": "VN",
      "company": "",
      "comments": "<![CDATA[]]>",
      "passport": null,
      "nationality": null,
      "profileId": 0
    }
  ],
  "contactInfos": [
    {
      "contactID": 856161,
      "key": "856161",
      "personOrgID": 695079,
      "contactField": "+84979206870",
      "contactType": 0,
      "extension": "",
      "countryCode": "",
      "areaCode": "",
      "phoneNumber": "",
      "display": null,
      "preferredContactMethod": true
    },
    {
      "contactID": 856162,
      "key": "856162",
      "personOrgID": 695080,
      "contactField": "+84979206870",
      "contactType": 0,
      "extension": "",
      "countryCode": "",
      "areaCode": "",
      "phoneNumber": "",
      "display": null,
      "preferredContactMethod": true
    },
    {
      "contactID": 856163,
      "key": "856163",
      "personOrgID": 695081,
      "contactField": "nhnhan@gmail.com",
      "contactType": 4,
      "extension": "",
      "countryCode": "",
      "areaCode": "",
      "phoneNumber": "",
      "display": null,
      "preferredContactMethod": true
    },
    {
      "contactID": 856160,
      "key": "856160",
      "personOrgID": 695079,
      "contactField": "+84979206870",
      "contactType": 2,
      "extension": "",
      "countryCode": "",
      "areaCode": "",
      "phoneNumber": "",
      "display": null,
      "preferredContactMethod": false
    },
    {
      "contactID": 856159,
      "key": "856159",
      "personOrgID": 695079,
      "contactField": "nhnhan@gmail.com",
      "contactType": 4,
      "extension": "",
      "countryCode": "",
      "areaCode": "",
      "phoneNumber": "",
      "display": null,
      "preferredContactMethod": false
    }
  ],
  "vouchers": [],
  "cars": [],
  "hotels": [],
  "packages": [],
  "exceptions": [
    {
      "exceptionCode": 0,
      "exceptionDescription": "Successful Transaction",
      "exceptionSource": "RetrievePNR",
      "exceptionLevel": 0
    }
  ],
  "totalCommission": 0
};
